# Generated by Django 6.0.3 on 2026-03-13 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComfyJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('prompt_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('output_files', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='comfyui_com_created_782647_idx'), models.Index(fields=['generation_id'], name='comfyui_com_generat_164c0a_idx'), models.Index(fields=['prompt_id'], name='comfyui_com_prompt__8600a0_idx')],
            },
        ),
    ]
